# Generated by Django 3.1 on 2020-08-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_auto_20200824_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
