# Generated by Django 3.1 on 2020-08-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
