# Generated by Django 2.2.8 on 2020-09-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20200829_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
