# Generated by Django 2.2.8 on 2020-09-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_remove_question_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('poet', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tester',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.Habit'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
