# Generated by Django 2.2.8 on 2020-09-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20200903_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='poet',
        ),
    ]
