# Generated by Django 2.2.8 on 2020-09-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_remove_habit_poet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt5',
        ),
    ]
