# Generated by Django 2.2.8 on 2020-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_remove_question_opt5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.TextField(),
        ),
    ]
