# Generated by Django 2.2.8 on 2020-08-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200826_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
