# Generated by Django 2.2.8 on 2020-08-27 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20200827_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meet_writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meet_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
