# Generated by Django 3.1 on 2020-08-26 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_meet_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='made_on',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 15, 25, 45, 290005)),
        ),
        migrations.AddField(
            model_name='order',
            name='made_on',
            field=models.DateField(default=datetime.datetime(2020, 8, 26, 15, 25, 45, 290005)),
        ),
    ]
