# Generated by Django 2.2.8 on 2020-08-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_meet_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='meet_writer',
        ),
    ]
