# Generated by Django 3.1 on 2020-08-26 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200826_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='made_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='made_on',
        ),
        migrations.AddField(
            model_name='item',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
