# Generated by Django 3.1 on 2020-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200826_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='날짜'),
        ),
    ]
