# Generated by Django 3.1 on 2020-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200826_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.TimeField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.TimeField(blank=True, null=True, verbose_name='날짜'),
        ),
    ]
