# Generated by Django 3.1 on 2020-08-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200826_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
